[package]
name = "exec-impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1"
proc-macro2 = "1"
prettyplease = "0"
