name: feature-matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "the feature matrix"
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    name: Generate feature matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compute feature matrix
        id: compute-matrix
        run: |
          cargo install cargo-feature-combinations
          echo "matrix=$(cargo feature-combinations matrix)" >> $GITHUB_OUTPUT
