name: validate
on: [push, pull_request]
jobs:
  test:
    name: validate (${{ matrix.command }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ["simulate", "accelsim-simulate"]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install accelsim dependencies
        run: >-
          sudo apt-get install -y wget build-essential xutils-dev bison zlib1g-dev flex libglu1-mesa-dev libssl-dev libxml2-dev libboost-all-dev git g++
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.10
        id: cuda-toolkit
        with:
          cuda: "11.8.0"
          method: "network"
          use-github-cache: true
          # list of available packages here:
          # https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/
          sub-packages: '["nvcc", "runtime", "profiler-api"]'
      - name: Build
        run: cargo build -p validate --all-targets
      - name: Build benchmarks
        run: ./target/debug/validate build
      - name: Run benchmarks
        run: ./target/debug/validate ${{ matrix.command }}
